### PR TITLE
fix for oF 0.11.2

### PR DESCRIPTION
**Pull request by themancalledjakob**
some minor adjustments to make it work in current oF

### CODE REVIEW

**Comment by kalwalt** [comment]
Hi @themancalledjakob thank you for this! Because i'm not using OF from a while can you add some more infos about your changes? Anyway i will test your code, Should i use OF version 0.11.2?
Thank you
Walter

**Comment by themancalledjakob** [comment]
hey @kalwalt ,

sure!
I changed the minimum amount I think to make it work. I think it pretty much boils down to this:
- add noisepp lib folder, so that the source is found automatically
- move example folder one level down
- rename testApp -> ofApp
- declare `noisepp::utils::GradientRenderer gradients;` in ofApp.h of the example
- use `getPix = m_image.getPixels().getData();` in `src/ofxNoisepp.cpp` to get access to the pixel data (this apparently changed)
- forget to disable auto linter, so the files are _beautified_ wherever I changed something ;) sorry about that

it should work with 0.11.2, as this is what I was testing with. I tested on linux and emscripten. I wouldn't expect it to be different for windows/mac.

**Comment by kalwalt** [comment]
> hey @kalwalt ,
> 
> sure!
> I changed the minimum amount I think to make it work. I think it pretty much boils down to this:
> - add noisepp lib folder, so that the source is found automatically
> - move example folder one level down
> - rename testApp -> ofApp
> - declare `noisepp::utils::GradientRenderer gradients;` in ofApp.h of the example
> - use `getPix = m_image.getPixels().getData();` in `src/ofxNoisepp.cpp` to get access to the pixel data (this apparently changed)
> - forget to disable auto linter, so the files are _beautified_ wherever I changed something ;) sorry about that
> 
> it should work with 0.11.2, as this is what I was testing with. I tested on linux and emscripten. I wouldn't expect it to be different for windows/mac.

Thank you, i will review your code this week. Happy easter!🐣🕊️

**Comment by themancalledjakob** [comment]
Cool :-) also happy easter!

**Comment by kalwalt** [comment]
@themancalledjakob i have tested you PR under Windows, creating a new project with the projectGenerator. I used VisualStudio Microsoft Visual Studio Community 2022 (64 bit) - Current
Version 17.5.4. All went fine, but i found few things to fix if you can. I will leave some comments directly in the code. I hadn't the time to test under linux64 (Ubuntu) i'm out of my linux machine at the moment maybe i will do in a near future.

**Comment by kalwalt** [comment]
Can you remove also all the obj files, the executable file and other files created by the compiler?
You can also remove the `test.pipeline` file in the `ofxNoiseppExample/bin` folder, actually the app use that one in `ofxNoiseppExample/bin/data`. If you make these changes i will happy to merge it. 🙂

**Comment by themancalledjakob** [comment]
hey @kalwalt , thanks for looking into this.

> @themancalledjakob i have tested you PR under Windows, creating a new project with the projectGenerator. I used VisualStudio Microsoft Visual Studio Community 2022 (64 bit) - Current
> Version 17.5.4. All went fine, but i found few things to fix if you can. I will leave some comments directly in the code. I hadn't the time to test under linux64 (Ubuntu) i'm out of my linux machine at the moment maybe i will do in a near future.

no worries, I have a variety of linux machines at hand (Ubuntu, Debian, Fedora), and will run it there to test.

> Can you remove also all the obj files, the executable file and other files created by the compiler?

absolutely, i must've overlooked that. they shouldn't be in there.

not entirely sure when i have time to do this, but it's on my bucket list ;-)

**Comment by themancalledjakob** [comment]
hey,

since it was not too many changes I decided to just re-apply them again in a new branch and send a second PR #2 . It should be pretty much the same changes, but without linting and undesired files.

I tested on linux, and it seems all good.

**Comment by kalwalt** [comment]
Ok @themancalledjakob i will review your PR. 🙂

**Pull request closed without merging**
